### PR TITLE
fixed memory leak on nginx reload

### PR DESCRIPTION
**Pull request by lneto**
* created a root pool to destroy modsec pool safely among reloads

### CODE REVIEW

**Comment by lneto** [comment]
Please, don't merge yet. A new PR is comming ;-).

**Comment by zimmerle** [comment]
Just to keep registered here, we have being discussing about those changes and @lneto is preparing some modifications on the patches that belongs to that Pull Request. I will close it as a new Pull Request is coming. Thank you @lneto.

**Comment by daniilyar-confyrm** [comment]
@zimmerle, as there is no link to new pull request you are referring to, I am asking here:
we face the said memory leak with ModSec 2.9.0 compiled from code with Nginx 1.8.0:
```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          2.0G       1.8G       137M       692K       157M       411M
-/+ buffers/cache:       1.3G       706M
Swap:           0B         0B         0B
$ free -h
             total       used       free     shared    buffers     cached
Mem:          2.0G       1.8G       137M       692K       157M       411M
-/+ buffers/cache:       1.3G       706M
Swap:           0B         0B         0B
$ free -h
             total       used       free     shared    buffers     cached
Mem:          2.0G       1.8G       137M       692K       157M       411M
-/+ buffers/cache:       1.3G       706M
Swap:           0B         0B         0B
$ pkill -HUP nginx
$ free -h
             total       used       free     shared    buffers     cached
Mem:          2.0G       1.8G       128M       692K       157M       411M
-/+ buffers/cache:       1.3G       697M
Swap:           0B         0B         0B
```

**Comment by daniilyar-confyrm** [comment]
Oops, soory, missed the opened https://github.com/SpiderLabs/ModSecurity/issues/895, added my question there

**Comment by zimmerle** [comment]
Hi @daniilyar-confyrm,

As you may able to see by @lneto comments, he is preparing some modifications to send another pull request.

We are currently working in a new version of ModSecurity, version 3. This version 3 works in a different fashion fixing not only this issue, but other related to this nginx implementation.

There are further information about libModSecurity here: http://tinyurl.com/zdyhgxk

**Comment by lneto** [comment]
Actually, I was; but it turns out that I couldn't come out with a
proper fix. Sorry =/. I think libModSecurity is a better approach.

Regards,
-- 
Lourival Vieira Neto

**Comment by daniilyar-confyrm** [comment]
@zimmerle, @lneto, thank you for an update. 
After you answers I have only one question: 
@zimmerle, are you going to merge at least critical fixes (like fixes for memory and file descriptor leaks) to 2.9?

**Comment by zimmerle** [comment]
Hi @daniilyar-confyrm,

Currently all the critical issues are merged into the "nginx_refactoring" branch. This branch won't be released. The version 2.9.1-RC1 will be release tomorrow (if everything goes right), but with no updates to nginx version.

That particular fixes are not merged because they may lead to other problems, currently they are only affecting dynamic configuration such as yours. Thus, very restrict set of users.

Keep tuned on the libModSecurity updates, i think it seems promising to your infrastructure.

**Comment by daniilyar-confyrm** [comment]
> Currently all the critical issues are merged into the "nginx_refactoring" branch
@zimmerle, using this branch at PROD is not acceptable for us as there is a lot of refactoring changes in this branch not qualified by community.. So I am going to fork the 2.9.0 version and apply only critical fixes to it (fix for memory leak and probably FDs leak). I will post the link to my fork here when done

**Pull request closed without merging**
