### PR TITLE
fix include

### PR DESCRIPTION
**Pull request by 877509395**
Fix lex "include [ \t]filename" handle. To support more spaces/tabs after include key word. Before this change, code supports only one space after include. but lex support more.

### CODE REVIEW

**Comment by martinhsv** [comment]
I like the simplification of leaving out regex.h.

But I don't think you need to make a copy.  For example, for the first of the two sections, wouldn't this suffice?:
```
char *tmpStr = yytext + strlen("include");
const char *file = strtok ( tmpStr, " \t");
```

**Comment by 877509395** [comment]
strtok(str) will set the next byte of last byte of token to '\0' if token found, so it may change the str. If str contains multiple [ \t], and we need enumerate  all possible tokens(call strtok multiple times), multiple bytes would be set to 0. below is a example.

</br>#include <string.h>
int main () {
   &nbsp;&nbsp;char str[80] = "This is - www.runoob.com - website";
   &nbsp;&nbsp;const char s[2] = "-";
   &nbsp;&nbsp;int i=0;
   &nbsp;&nbsp;char *token;
   &nbsp;&nbsp;int length;
   &nbsp;&nbsp;length = strlen(str);
   &nbsp;&nbsp;token = strtok(str, s); 
   &nbsp;&nbsp;while( token != NULL ) { 
   &nbsp;&nbsp;&nbsp;&nbsp;i++;
   &nbsp;&nbsp;&nbsp;&nbsp;printf( "token%d        =%s\n", i,token );
   &nbsp;&nbsp;&nbsp;&nbsp;printf( "token%d address=%p\n", i, token );  
   &nbsp;&nbsp;&nbsp;&nbsp;token = strtok(NULL, s); 
   &nbsp;&nbsp;&nbsp;&nbsp;printf("\n");
   &nbsp;&nbsp;}   
   &nbsp;&nbsp;printf( "str          =%s\n",str);
   &nbsp;&nbsp;printf( "str          =%p\n", str  );  
   &nbsp;&nbsp;return(0);
}

the output is:
token1        =This is 
token1 address=0x7ffe0e856810

token2        = www.runoob.com 
token2 address=0x7ffe0e856819

token3        = website
token3 address=0x7ffe0e85682a

str          =This is 
str          =0x7ffe0e856810
~                
From the output, str is changed to "This  is", the next byte of "This is"  changed to 0. every token address is between str and str+length;  

For our case, strtok only is called only once, and based on the below grammar, it is NOT possible there is a [ \t]+ in "CONFIG_VALUE_PATH", so strtok will not change CONFIG_VALUE_PATH LUCKILY;
"CONFIG_VALUE_PATH                       [0-9A-Za-z_\/\.\-\*\:]+"
{CONFIG_INCLUDE}[ \t]+{CONFIG_VALUE_PATH}
{CONFIG_INCLUDE}[ \t]+["]{CONFIG_VALUE_PATH}["]

so below change can suffice.
  char *tmpStr = yytext + strlen("include");
  const char *file = strtok ( tmpStr, " \t");

But I think it is a good practice to first strdup and then free for strtok： 
1. strtok may do harm to  input.
2. In case for some reason in the future, CONFIG_VALUE_PATH can contain space/tab. 
3. hidden logic(can not contain space/tab in CONFIG_VALUE_PATH) of the code need to dig out

**Comment by martinhsv** [comment]
Ok, good point.  I agree that it's unwise to use strtok here without a copy.

Is it worth considering using strspn instead?  It's a little more narrowly focussed on what is needed here.

```
char *tmpStr = yytext + strlen("include");
const char file = tmpStr + strspn ( tmpStr, " \t");
```

**Comment by 877509395** [comment]
Perfect, strspn exactly matches this context. I think I should go through libc.pdf to know every function.
</br>
remove tmpStr, merge two lines into  one line:

const char *file = yytext + strlen("include")+ strspn ( yytext + strlen("include"), " \t");

Is it OK to remove tmpStr?

**Comment by 877509395** [comment]
#include <stdio.h></br>
#include <string.h>
int main(int argc, char**argv)
{
&nbsp;&nbsp;const char *yytext = "include           lj lj ljsdfj";
&nbsp;&nbsp;const char *file = yytext + strlen("include")+ strspn ( yytext + strlen("include"), " \t");
&nbsp;&nbsp;printf("%s", file);
}
the output is:
[root@localhost strcspn]# ./a.out 
lj lj ljsdfj

**Comment by 877509395** [comment]
BTW,
Same issue also seems exists in many other line. for example,
{CONFIG_DIR_AUDIT_LOG2}[ \t]+{CONFIG_VALUE_PATH}                        { return p::make_CONFIG_DIR_AUDIT_LOG2(strchr(yytext, ' ') + 1, *driver.loc.back());
I have not check it carefully now.

**Comment by 877509395** [comment]
misoperation close this PR and delete lexhandle

**Comment by martinhsv** [comment]
Regarding collapsing the code change to a single line, I might lean towards leaving it as two lines, because:
- allocating an extra pointer on the stack doesn't really create extra cost or risk and
- it may make the code a little bit easier to read and
- it avoids duplicating code `strlen("include")` ... including having a hard-coded string specified twice; it's generally a good coding practice to avoid such duplication

My preference on that isn't particularly strong, however,

**Comment by 877509395** [comment]
reasonable

**Comment by 877509395** [comment]
will submit PR tomorrow

**Pull request closed without merging**
