### PR TITLE
audit_log improvements

### PR DESCRIPTION
**Pull request by phantom-az**
Felipe,

There's an implementation of missing AuditLog support parts -E-, -H- & -K-.  As per our discussion it's conditionally compiled.

https://github.com/SpiderLabs/ModSecurity/commit/045317601206aa89d1d293f4694d83b0900a89e3
https://github.com/SpiderLabs/ModSecurity/commit/aa7e499ec3a6a8de7626e7fe8e0cf870611cafbe

### CODE REVIEW

**Comment by defanator** [comment]
First, I'd like to advise you to create a separate branch for each PR to avoid mess with unrelated commits. :)

Second, I have tested 0453176 and aa7e499, and the observed behavior doesn't seem right: I see that every consequent non-blocked request contains "H" section contents from previous blocked request.

See this gist for details:
https://gist.github.com/defanator/5ef589e842dd2bd1b6278552ee1e6f2a

**Comment by defanator** [comment]
I have also added "K" section to the audit log configuration, and it doesn't appear:
https://gist.github.com/defanator/5ef589e842dd2bd1b6278552ee1e6f2a#file-02modsec_audit_k-log

**Comment by defanator** [comment]
Same for "E" section (request body), it also doesn't appear:
https://gist.github.com/defanator/5ef589e842dd2bd1b6278552ee1e6f2a#file-03modsec_audit_e-log

("SecRequestBodyAccess" is enabled, modsecurity.conf is the default one)

**Comment by zimmerle** [comment]
To whom it may concern, we are discussing this via Slack: http://modsecurity.slack.com

**Pull request closed without merging**
