### PR TITLE
Fix sanitizing JSON request bodies in native audit log format

### PR DESCRIPTION
**Pull request by p0pr0ck5**

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Hey @zimmerle any thought of aligning this with the 2.9.3 milestone?

**Comment by zimmerle** [comment]
Sure. done.

**Comment by Artistan** [comment]
will this allow the body to be JSON formatted?

**Comment by p0pr0ck5** [comment]
Ping @zimmerle. Any thoughts on merging this in and tagging a new 2.9.x release?

**Comment by victorhora** [comment]
Merged. Thanks!

**Pull request merged**
