### PR TITLE
Optimize duplicate rule ID check

### LINKED ISSUE #1663: Huge memory consumption and slow nginx configtest/start/restart with ModSecurity v3 and ModSecurity-nginx
Hellow everybody.

I am trying to make modsecurity 3 + modsecurity-nginx connector working on my setup with ~2000 vhosts and ~3000+ rules.

Compilation configuration etc. are all fine **but** when I try to run nginx **configtest**/**start**/**restart** it it is taking ages (5,8,10 **minutes**) for each of the operations to complete.

Also during the configtest and after the restart nginx is consuming **huge** amount of memory talking GBs here.

The problem(s):

nginx -t is taking ages
nginx restart/reload is taking even more time
nginx is consuming huge amount of memory (talking GBs here)

At first it sounds very similar to https://github.com/SpiderLabs/ModSecurity/issues/1546 but it is not. The the patches mentioned there are already applied in my build.

Also I am not really sure if this is a memory leak bug at all or something that is not very well optimized for use cases like mine.

I am also using apache 2.4.x with modsecurity 2.x with the **very same** rule-set and configtest/start/restart operations are completed in matter of (sub)seconds with the same amount of virtual hosts. 

Here is a quick look at the ltrace of nginx -t which I think might be useful for you. It is showing excessive amount of calls to **msc_rules_merge** which is taking most of the configtest time.

root@server.com:/etc/nginx# ltrace  -f -c nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
"% time     seconds  usecs/call     calls      function
------ ----------- ----------- --------- --------------------
 32.87 1783.733281         157  11349307 strncmp
 28.18 1529.493827  1529493827         1 __libc_start_main
 18.44 1000.688939       23966     41753 msc_rules_merge
  5.63  305.725415         162   1882658 strcmp
  4.99  270.902396         158   1711981 memset
  2.35  127.432618         171    743696 memcpy
  1.77   95.819104         160    598387 malloc

If you need more information please let me know. I will be happy to assist.

The setup:

- number of modsecurity rules: 3355
- number of nginx virtual hosts:  1779
- ModSecurity v3 VERSION - c1cd668acb820824e791ba802396c60900eae9c1
- ModSecurity v3 build options
`
./configure \
    --prefix=/usr/local \
    --enable-shared=yes \
    --with-geoip=no \
    --with-ssdeep=no \
    --with-lua=no \
    --with-libxml=/usr \
    --with-pcre=/usr/local/pcre-8.38 \
    --with-yajl=/usr/local/yajl-2.1.0 \
    --with-curl=/usr/local/curl-7.46.0
`
- ModSecurity-nginx connector v3 - c0ae166cc30c01b96147b6bc3d0cda708f5cdfb7
- nginx version: nginx/1.13.7
- nginx build options
`
--with-cc=/opt/rh/devtoolset-2/root/usr/bin/gcc
--prefix=/usr/local/nginx
--user=nginx
--group=nginx
--with-file-aio
--with-ipv6
--with-pcre
--with-http_addition_module
--with-http_degradation_module
--with-http_gzip_static_module
--with-http_random_index_module
--with-http_realip_module
--with-http_secure_link_module
--with-http_ssl_module
--with-http_stub_status_module
--with-http_sub_module
--with-http_v2_module
--without-http_ssi_module
--without-mail_imap_module
--without-mail_pop3_module
--without-mail_smtp_module
--conf-path=/etc/nginx/nginx.conf
--error-log-path=/var/log/nginx/error.log
--http-log-path=/var/log/nginx/access.log
--http-client-body-temp-path=/var/cache/nginx/tmp/client_body
--http-proxy-temp-path=/var/cache/nginx/tmp/proxy
--http-fastcgi-temp-path=/var/cache/nginx/tmp/fastcgi
--http-uwsgi-temp-path=/var/cache/nginx/tmp/uwsgi
--http-scgi-temp-path=/var/cache/nginx/tmp/scgi
--pid-path=/var/run/nginx.pid
--lock-path=/var/lock/subsys/nginx
--with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic'
--with-ld-opt=-Wl,-E
--with-openssl=submodules/openssl
--add-module=submodules/ngx_pagespeed-1.12.34.3-stable
--add-module=submodules/cache_purge
--add-module=submodules/testcookie
--add-module=submodules/nginx-module-vts
--add-module=submodules/ModSecurity-nginx
`
- modsecurity is enabled in the nginx configuration directly in the http block (tried that in each vhost separately which seems to make the things and memory consumption even worse)
`
http {
    modsecurity on;
    modsecurity_rules_file /etc/nginx/mod_security2.conf;
    .....
}
`

### PR DESCRIPTION
**Pull request by p0pr0ck5**
Replace an expotential search function with a stl set search.

### CODE REVIEW

**Comment by zimmerle** [comment]
As already commented on #1667, disable the check or make it faster does not fix the issue #1663, instead put it under the carpet. IMHO, the problem is a race condition related to the nginx worker life cycle.

This patch fix a symptom not the real problem. In a different setup (amount of rules, memory, vhosts, etc...) the problem is likely to appear again.

As this is the current most notice symptom for the worker life cycle problem, I am holding on the merge till we fix the main problem.

**Comment by p0pr0ck5** [comment]
Updated the commit message to remove the reference to #1663. This may have tangential impact but we do not consider it a fix for the issue noted at this time.

**Comment by p0pr0ck5** [comment]
@zimmerle curious as to your thoughts here, is this still being considered for merge at all?

**Comment by zimmerle** [comment]
Hi @p0pr0ck5,

I am sorry for the delay with this review. I am afraid we won't be able to merge the patch as is. It took a while because I think you deserve to know in details why I am not accepting it, and I just had the chance to write about it today.

In a simple paragraph: The description of the patch doesn't seem strictly accurate, I'm failing to see an exponential problem (not in this case). Your patch effectively improved the speed  by creating a cache structure to easily find duplicate IDs, at the cost of memory usage which 
is also computationally expensive, especially in the use case that we are aiming to target. Just to be clear, the usage of memory here will be allocated till the ModSecurity process finish.

One thing that we do agree with you is that there is space for improvements in this articular piece of code. But first let me go over the gory technical details to widen our audience.


**The Problem Description**

In the commit message there's a mention about the search function being exponential. Just so we're all on the same page, In Big-O notation something is exponential when the time to process increases exponentially by the amount of inputs. For instance, the Selection Sort which is O(n^2) in best, average and worst case. This is not the case of this ModSecurity function as it have a "_for_" inside a "_for_" with two different sets.

Exponential Search is also the name of a very popular search algorithm for infinity sets, which is actually O(log i) in average time complexity. I guess you are not referring to that either.

That is the theoretical part of the review, as in practice, it may lead to a exponential problem, Let's test that in the field. Fortunately, that is not the case either. I will explain: At this point I would like to introduce the test app called _load.cc_, it is meant to help us testing the numbers in practice. It could be used by anyone that also wants to help us during this process.


**The load.cc app**

The _load.cc_ app stress the mechanism in question with (almost) zero interferences of other components, in order to give us better comparative results and how much improvement was really made. 

The app is available here:
https://gist.github.com/zimmerle/e90054b7630099e7aceceb8f0431f754

It does mimic a use case when a giant rule set is loaded and folders and/or vhosts are merged with their rules with the intention of tuning the main rule set. All stressed with an abnormal amount of rules.

**Checking if there is any exponential problem at all**

Using the _load.cc_ tool we can confirm that the merge/loading time is not actually 
 exponential, but linear. The image below highlight what is happening in our implementation.

chart1
**Figure 1.** Using _load.cc_ to grab the timing to load the rule set.

The conclusion is very clear: there is no exponential problem. Not theoretical,
not practical. Yet let's continue to analyze the patch to understand what are the benefits of it and how it can be further improved.


**Understanding the patch**

There is a change in the function signature: instead of receiving the original
object it does receive the child one:

https://github.com/SpiderLabs/ModSecurity/pull/1735/commits/08f9a7fcb3d0ab34d214346c3f23d60c7e280454#diff-06c9e7fe9d6fb2c786762bf46bccad96L429

And here some variable renaming:

https://github.com/SpiderLabs/ModSecurity/pull/1735/commits/08f9a7fcb3d0ab34d214346c3f23d60c7e280454#diff-06c9e7fe9d6fb2c786762bf46bccad96L434

I believe the goal on both aforementioned changes is not improving the performance. Moving on... Here we have some an important logical change:

https://github.com/SpiderLabs/ModSecurity/pull/1735/commits/08f9a7fcb3d0ab34d214346c3f23d60c7e280454#diff-06c9e7fe9d6fb2c786762bf46bccad96L438

There is the replacement of one _for_ loop with a _std::find_ that loops on this new structure called _m_ruleIds_. The structure itself was declared here:

https://github.com/SpiderLabs/ModSecurity/pull/1735/commits/08f9a7fcb3d0ab34d214346c3f23d60c7e280454#diff-06c9e7fe9d6fb2c786762bf46bccad96R501

So, the patch effectively creates a caching structure that holds the data for a 
faster look-up.


**Is there a benefit to apply that patch?**

There is a real benefit to apply this patch. It will speed up the rules loading process a little. Depending on the scenario, it could be as fast as 2x. However it does use memory in a non ideal shape, as it stores something in memory that is already in memory: **the rule id.**

So, let's read the patch again to understand the real need for this caching.

The problem is definitely this for on line 438: 
https://github.com/SpiderLabs/ModSecurity/pull/1735/commits/08f9a7fcb3d0ab34d214346c3f23d60c7e280454#diff-06c9e7fe9d6fb2c786762bf46bccad96L438.

So, we thought that instead of creating a caching to persist for the existence of the process, why not to create a stack cache disposed by the end of this validation?

That was exactly what was done here: 
https://github.com/SpiderLabs/ModSecurity/blob/65aa7ae5e2686caf7c530c1cae08bcfcfb1f15c8/headers/modsecurity/rules_properties.h#L433-L464

Notice that it is not optimal, it is using _std::binary_search_ in a _std::vector_, in reality we just need to have a simple array and store the integers for a fast check, but i guess it is safe to live with it now. The charts below illustrates in details all the concerns that were raised during this study.

chart2
**Figure 2.** Loading time, first 100 merges.

chart5
**Figure 3.** Memory usage.

Having said all that, we hereby thanks @p0pr0ck5 for the work invested in this patch, for bringing this issue to light allowing us to invest more time improving it. Therefore we are proceeding to close it without accepting fully for the reasons pointed out above. Instead, we've added the modifications linked here to the master branch. We're open to any question or concerns that anyone may have.

**Comment by p0pr0ck5** [comment]
Hey @zimmerle,

Thanks for the detailed write up. However I wanted to highlight something from your findings that does not correctly demonstrate the originally reported behavior (within the C API, and thus the Nginx connector). I found significantly different results when using a C harness instead of a C++ program to load many rulesets as laid out here: https://gist.github.com/p0pr0ck5/c5045eb3b6107917db771be3ef1df08b. The C harness shows behavior that is indeed exponential (please bear the very basic mock/graph):

```
$ for i in 100 200 300 400 500 600 700 800 900 1000; do ./load-c $i; done
took 670.073975
took 2194.941895
took 5914.875000
took 15941.778320
took 31686.080078
took 54498.371094
took 84973.710938
took 125235.476562
took 178898.796875
```

exp-modsec-load-rules

I believe the reason for this is that your mock creates a _new_ `Rules` object, and appends to an existing `Rules`:

```
        modsecurity::Rules *a = new modsecurity::Rules();
         if (a->loadFromUri(fn(i).c_str()) < 0) {
            std::cout << "Problems loading the rules..." << std::endl;
            std::cout << a->m_parserError.str() << std::endl;
            return -1;
        }
        rules.push_back(a);
```

This is not the same behavior as leveraged by the C API, which implements a single `Rules` ptr: https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/rules.cc#L340-L347

Thus your benchmark doesn't demonstrate an exponential time because that behavior in question is not exponential. :) What _is_ exponential (or was, prior to `65aa7ae5e2686caf7c530c1cae08bcfcfb1f15c8`) was load many rules over an over into a _single_ `Rules`.

What's more, your example could not correctly detect a duplicate ID between two different rulesets, only duplicate IDs loaded within the same call to `loadFromUri`. :)

This is all a moot point now that the behavior has been modified, but I did want to bring to light the disparity between the behavior seen within Nginx (originally reported in #1663), and the test harness you wrote. Thanks!

**Pull request closed without merging**
