### PR TITLE
Refactoring conditional directives.

### PR DESCRIPTION
**Pull request by wmarquesr**
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.

* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)

It might improve code understanding, maintainability and error-proneness.

### CODE REVIEW

**Comment by csanders-git** [comment]
I'll leave this for @zimmerle but you should check out the the libmodsecurity branch as it has been rewritten with a more logical design and stricter coding standards defined.

**Comment by zimmerle** [comment]
Hi @wmarquesr,

Thank you for the patch. The code is currently in our BuildBots.

Same modifications are more than welcomed on LibModSecurity, available here:
https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity

**Comment by zimmerle** [comment]
Hi @wmarquesr,

I left a comment in the patch:
https://github.com/wmarquesr/ModSecurity/commit/b7b10b5c005cd41e4c7ce1c775d4e83f2b9a3a98#commitcomment-14883469

Can you fix this?

**Comment by wmarquesr** [comment]
All fixed. Sorry for the mistake.

**Comment by zimmerle** [comment]
Thank you @wmarquesr,

Patch is on our buildbots again.

**Comment by zimmerle** [comment]
Hi @wmarquesr,

Still interested to provide the fix ?

**Comment by wmarquesr** [comment]
All fixed, sorry for delay.

**Comment by zimmerle** [comment]
Hi @wmarquesr,

Thank you! Your patch was merged and will be released as part of ModSecurity v2.9.1.

The same kind of patch are very welcomed in ModSecurity version 3:
- https://www.trustwave.com/Resources/SpiderLabs-Blog/An-Overview-of-the-Upcoming-libModSecurity/
- https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/

**Pull request closed without merging**
