### PR TITLE
Make all "rule id" variables of type RuleId

### PR DESCRIPTION
**Pull request by WGH-**
Previously, ModSecurity inconsistently used int, int64_t and double for rule id variables in different places.

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi, @WGH-

Thank you for the patch. Apparently we have a similar patch on our development branch -
 - b8aae970158252800862b566216c0b4d54220f34

The dev branch is available here:  [v3/dev/3.1-experimental](https://github.com/SpiderLabs/ModSecurity/tree/v3/dev/3.1-experimental)

**Comment by WGH-** [comment]
Although similar in scope, that patch merely replaces `int64_t` with `RuleId` typedef, and it doesn't address `int` and `double` stuff.

**Comment by zimmerle** [comment]
I am not saying that one replaces the other. I am saying that both adds a benefit. It would be interesting to have your patch using the RuleId alias. Further, we can adjust the RuleId container size as needed. How do you fill about that?

**Comment by WGH-** [comment]
I can rebase the patch on top of v3/dev/3.1-experimental, if that's what you're saying.

By the way, there's a type called `RuleId` here: https://github.com/SpiderLabs/ModSecurity/blob/v3/dev/3.1-experimental/src/actions/rule_id.h. Wouldn't it create conflict with the newly introduced `RuleId` type alias?

> Further, we can adjust the RuleId container size as needed. How do you fill about that?

I'm not sure which RuleId container you're referring to.

**Comment by zimmerle** [comment]
There are: 
 - modsecurity::actions::RuleId
 - modsecurity::RuleId

Those are defined here:

https://github.com/SpiderLabs/ModSecurity/blob/5824470768e73d438a5db03b7a6eb24d7c795097/src/actions/rule_id.h#L32-L35

and

https://github.com/SpiderLabs/ModSecurity/blob/5824470768e73d438a5db03b7a6eb24d7c795097/headers/modsecurity/modsecurity.h#L98

Those are two different things, thanks for the [namespace](https://en.cppreference.com/w/cpp/language/namespace)

I meant a rebase, making sure that the type **RuleId** is used to refer to a _Rule Id_. Not **int_64**, not **double**. Only **RuleId**.

**Comment by WGH-** [comment]
Fair. I totally forgot about namespaces. I'll do a rebase on top of v3/dev/3.1-experimental then.

**Comment by zimmerle** [comment]
@WGH- thank you! That is an important change.

**Comment by WGH-** [comment]
Done. Some tests don't pass, but they don't pass in base v3/dev/3.1-experimental either.

**Comment by zimmerle** [comment]
> Done. Some tests don't pass, but they don't pass in base v3/dev/3.1-experimental either.

Thanks! Yep. You are likely to be referring to the XML tests. Have to fix that and rebase the tree accordingly. It is on my todo list, before making it w3/master.

**Comment by zimmerle** [comment]
Thank you @WGH-  this is now merged into 3.1-experimental.

**Pull request closed without merging**
