### PR TITLE
bro

### PR DESCRIPTION
**Pull request by ghost**
//

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi @krebsyba, how can we help?

**Comment by ghost** [comment]
Düzeltilmesini istiyorum

**Comment by zimmerle** [comment]
> Düzeltilmesini istiyorum

It is not clear to me what you want to fix or the add with this pull request. Can you give us a brief introductions of the benefits added on those changes?

**Comment by zimmerle** [comment]
There is no change from bazzadp/ModSecurity.git#b6053df to b6053df941f872b5c6ee8754837a8d5b21024769. Thefore closing this pull request.

**Pull request closed without merging**
