### PR TITLE
Force to send custom headers back to the client and fix POST 500 error

### PR DESCRIPTION
**Pull request by ton31337**
Custom headers are skipped when using nginx as proxy_pass to origin. They are displayed only in audit_log, but the client doesn't see them. For example X-Flash-Message header.

### CODE REVIEW

**Comment by jdoss** [comment]
I was getting 500 errors on POST and this fixed the problem. If there was a +1 button I would push it.

**Comment by ton31337** [comment]
Yes this patch solves 500 and x headers issues.

**Comment by bradcosine** [comment]
I can confirm that this resolved the POST 500 error. Thanks!

**Comment by zimmerle** [comment]
Hi @ton31337 the current version of our nginx_refactoring branch returns all the headers to the users, including those "X-Flash-Message", can you confirm that it is working for you?

**Comment by ton31337** [comment]
It misses new_h->hash = 1;
https://github.com/SpiderLabs/ModSecurity/blob/nginx_refactoring/nginx/modsecurity/ngx_http_modsecurity.c#L860

And we are getting 500 POST with SecRequestBodyAccess On. Need the last
commit from this PR:
https://github.com/SpiderLabs/ModSecurity/pull/826

On Tue, Mar 24, 2015 at 10:39 PM, Felipe Zimmerle <notifications@github.com>
wrote:

> Hi @ton31337 <https://github.com/ton31337> the current version of our
> nginx_refactoring branch returns all the headers to the users, including
> those "X-Flash-Message", can you confirm that it is working for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpiderLabs/ModSecurity/pull/826#issuecomment-85684056>
> .
>



-- 
Donatas

**Comment by zimmerle** [comment]
Not sure if I am look to the right commit. I am looking to this one:
https://github.com/ton31337/ModSecurity/commit/2bb9c0088e59a2cd43842e5a2ac99dd41308751e

The content is:
A) Line 1-9: Contain modifications on the file copyright.
B) Line 73: Adds the variable x_headers
C) Line 162-167: Adds the ModSecurityXHeaders command.
D) Line 547-550: returns if trying to set the header Host on the client (similar to what was suggested on #740)
E) Line 819-823: Reorganization of the variables declaration plus the addition of the tmp_header.
F) Line 843-856: Adding the header back to the client.
G) Line 1021 and 1035: Add support to configuration merge and set the default conf->x_headers value.

Is that correct?

If so, the blocks A, B, C, E, F and G will no longer be necessary as we are saving all the headers already. Only left the block "D" (also covered by #740) and the problem that you have mentioned about "new_h->hash = 1;".

Do you mind to share the scenario of the crash, it will be valuable. I can place it under our regression tests.

**Comment by uxbod** [comment]
Using @ton31337 branch for the XHeaders PR has resolved the 500 errors we were getting.  Even a simple wp-login.php POST was the error.

**Comment by ton31337** [comment]
@zimmerle I don't have now any chance to make you crash test, because I don't work for that company they are using ModSecurity, sorry.

**Comment by ton31337** [comment]
@zimmerle 
1. You can just use simple curl request with POST and test this case. (HTTP 500 issue)
2. Set your service (nginx/apache) with responding with header e.g. X-Rails-Message and see if you receive this header as a client. (Custom headers issue)

**Comment by ton31337** [comment]
@zimmerle should I rebase my branch or can I delete it at all (suppose you don't use it)?

**Comment by zimmerle** [comment]
Hi @ton31337, keep it here. It is used as a reference in too many issues now.

I am working on libmodsecurity - 
https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/

Expecting to solve all those bugs with this new version of ModSecurity.

**Comment by ton31337** [comment]
@zimmerle you should pay more attention on POST 500 error. Take a look at this line: https://github.com/ton31337/ModSecurity/commit/2bb9c0088e59a2cd43842e5a2ac99dd41308751e#diff-a80339e1bd9e20765a4f9539ae3c09ecR547 and about sending headers from back-end to browser there is missing https://github.com/ton31337/ModSecurity/commit/2bb9c0088e59a2cd43842e5a2ac99dd41308751e#diff-a80339e1bd9e20765a4f9539ae3c09ecR851.

**Comment by zimmerle** [comment]
Hi @ton31337, I would like to thank you again for the patches. I am closing this issue as pieces of your merge request was already merged into the nginx_refactoring branch. Thank you.

**Pull request closed without merging**
