### PR TITLE
Support PCRE2

### LINKED ISSUE #2668: Add support for PCRE2
The legacy PCRE implementation (more recently referred to as PCRE1) is no longer being updated, with v8.45 (from June 2021) expected to be the final version.

Also, nginx has recently (nginx/1.21.5) changed to use PCRE2 by default, and this will cause problems if not using the --without-pcre2 flag when building (see https://github.com/SpiderLabs/ModSecurity-nginx/pull/260, https://github.com/SpiderLabs/ModSecurity-nginx/pull/261 ).

### PR DESCRIPTION
**Pull request by martinhsv**
This pull request provides initial support for PCRE2 on an experimental basis. (Closes #2668 )

To use PCRE2 with nginx and ModSecurity you need to:
- use a version of nginx that supports it (e.g. nginx v1.21.5 or 1.21.6)
- use a version of the connector (ModSecurity-nginx) at or later than https://github.com/SpiderLabs/ModSecurity-nginx/commit/1c32794046c9e0065d4ad58f949fabb538c44222
- include the ```--with-pcre2``` option when running ModSecurity's ```./configure```

### CODE REVIEW

**Comment by istiak101** [comment]
Do I need to pass the PCRE2 path too? Explicit `--with-pcre2=yes` didn't work.

```
checking for libpcre config script... no
configure: *** pcre library not found.
configure: error: pcre library is required
```

I don't know it's using build/pcre.m4 instead of build/pcre2.m4

**Comment by istiak101** [comment]
So PCRE1 config binary location is /usr/bin/pcre-config and PCRE2 config binary /usr/bin/pcre2-config.
In PCRE1 the config script is detected correctly but not with PCRE2.

**Comment by dvershinin** [comment]
@istiak101 @martinhsv apparently there's a bug somewhere.

`--with-pcre2` only compiles fine if both pcre1 and pcre2 devel libs installed. And the resulting binary links with both, which is incorrect, of course.

If only pcre2 devel is installed on the system, the error message  during configure is always `configure: error: pcre library is required`.

See filed new bug https://github.com/SpiderLabs/ModSecurity/issues/2750

**Comment by martinhsv** [comment]
Hello @istiak101 ,

As @dvershinin has noted, the dependency on pcre1 has not been removed even if you specifically want to use pcre2. But beyond that, does it work if you just use (although =yes should work too):
```
./configure --with-pcre2
```

**Comment by istiak101** [comment]
Hello @martinhsv,

Yes if install both pcre-devel and pcre2-devel it works.

**Pull request merged**
