### PR TITLE
fix using relevant statuses + noauditlog

### PR DESCRIPTION
**Pull request by AirisX**

### CODE REVIEW

**Comment by martinhsv** [comment]
Closing for the reasons in the related issue (incuding that this pull request would break DetectionOnly functionality).

**Comment by AirisX** [comment]
Hi @martinhsv ,
Why are you sure this PR would break DetectionOnly functionality? In my recent posts here https://github.com/SpiderLabs/ModSecurity/issues/2637 I have provided example code that preserves this functionality:
```
if ((m_status == RelevantOnlyAuditLogStatus
        && this->isRelevant(transaction->m_httpCodeReturned) == false
        && transaction->getRuleEngineState() != static_cast<int>(RulesSetProperties::DetectionOnlyRuleEngine)) 
        || saveAnyway == false ) {
```

**Comment by martinhsv** [comment]
But that sample code is not part of this PR.  This PR, as it stands, cannot be merged because it would break functionality.

You are welcome to submit a fresh pull request for consideration along the lines of what I described in #2637.

**Comment by AirisX** [comment]
I planned to include these lines after the discussion in # 2637.  Ok, I'll open the new PR to include lines above

**Comment by 877509395** [comment]
hi,


Seems below command not supported by ModSecurity. Even if a small /file/path/file-name&nbsp;


curl -F "filename=@/file/path/file-name"&nbsp; www.test5.com


modsecurity create two transactions for this request, I think it should not, it should be one request one transaction.&nbsp;


mod version: 3.0.6
mod-nginx-connector: 1.0.2
core-rule-set:&nbsp;3.4.0


Below json will be triggerred.&nbsp; &nbsp;
{
&nbsp;&nbsp;&nbsp;&nbsp;"source":"modsecurity",
&nbsp;&nbsp;&nbsp;&nbsp;"type":"attack",
&nbsp;&nbsp;&nbsp;&nbsp;"mId":"104617fcd945_172.18.0.2",
&nbsp;&nbsp;&nbsp;&nbsp;"client_ip":"172.18.0.1",
&nbsp;&nbsp;&nbsp;&nbsp;"time_stamp":"Tue&nbsp;Dec&nbsp;21&nbsp;10:42:54&nbsp;2021",
&nbsp;&nbsp;&nbsp;&nbsp;"server_id":"cc57a40222759adedd87fbb5e0f450fd4d103a60",
&nbsp;&nbsp;&nbsp;&nbsp;"version":"commit&nbsp;85b176b5e39d513985e3455f908688e525bfe061",
&nbsp;&nbsp;&nbsp;&nbsp;"client_port":58302,
&nbsp;&nbsp;&nbsp;&nbsp;"host_ip":"172.18.0.2",
&nbsp;&nbsp;&nbsp;&nbsp;"host_port":80,
&nbsp;&nbsp;&nbsp;&nbsp;"unique_id":"1640083374",
&nbsp;&nbsp;&nbsp;&nbsp;"http_version":1.1,
&nbsp;&nbsp;&nbsp;&nbsp;"uri":"/",
&nbsp;&nbsp;&nbsp;&nbsp;"http_code":403,
&nbsp;&nbsp;&nbsp;&nbsp;"server_name":"www.test5.com",
&nbsp;&nbsp;&nbsp;&nbsp;"method":"GET",
&nbsp;&nbsp;&nbsp;&nbsp;"request":{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"body":"",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"headers":{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Host":"www.test5.com",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"User-Agent":"curl/7.80.0",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Accept":"*/*",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Content-Length":"348",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Content-Type":"multipart/form-data;&nbsp;boundary=------------------------34484de1b7a90294"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;"response":{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"body":"",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"http_code":403,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"headers":{

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;"messages":[
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"attackName":"GET&nbsp;or&nbsp;HEAD&nbsp;Request&nbsp;with&nbsp;Body&nbsp;Content",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"details":{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"match":"Matched&nbsp;\"Operator&nbsp;`Rx'&nbsp;with&nbsp;parameter&nbsp;`^0?$'&nbsp;against&nbsp;variable&nbsp;`REQUEST_HEADERS:Content-Length'&nbsp;(Value:&nbsp;`348'&nbsp;)",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"reference":"o0,3v0,3v87,3",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"ruleId":"920170",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"data":"348",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"severity":"2",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"action":"block&nbsp;and&nbsp;log",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"attackClass":"PROTOCOL"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;]
}












huiming

**Comment by martinhsv** [comment]
Hello @877509395 ,

I would encourage you to not post unrelated content into PRs or issues.  Since such issues and PRs persist, it's helpful if each PR or issue only contains postings relevant to it.

Regarding your assertion, if you think you have identified some anomaly certainly feel free to open an issue for it. In this case, however, I would suggest more investigation on your part would be in order. You state that 'modsecurity create two transactions for this request'. That is unlikely. If a second transaction is being processed, it is much more likely that it is being created some other way such as through nginx configuration that includes error redirects. See for example https://github.com/SpiderLabs/ModSecurity-nginx/issues/152#issuecomment-583037424

**Pull request closed without merging**
