### PR TITLE
Move APLOG_USE_MODULE out of modsecurity.h

### PR DESCRIPTION
**Pull request by erkia**

### CODE REVIEW

**Comment by marcstern** [comment]
Putting it in apache2.h solves the problem in a cleaner way

**Comment by erkia** [comment]
> Putting it in apache2.h solves the problem in a cleaner way

I kind of agree, but my first try to solve it in a cleaner way failed, so I'm a bit cautious to add it again in a header file...

**Comment by marcstern** [comment]
I tried in msc_logging.h and it works: extensions can compile and all needed files include it

**Comment by marcstern** [comment]
Indeed, apache2.h (as most of other .h files) is inherited as well

**Comment by martinhsv** [comment]
All right, this PR seems like a reasonable way to proceed.

If no one raises any objections, I'll plan to merge this before the end of the day.

**Comment by martinhsv** [comment]
Thanks @marcstern , for raising that detail on such a timely basis.

And thanks @erkia for providing the adjustment.

**Pull request merged**
