### PR TITLE
fix for issue 630

### PR DESCRIPTION
**Pull request by kyprizel**
Host header handler can't be run from this stage

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi @kyprizel, are you still interested on this pull request? 

If you are not interested I may continue your work. I just need to understand it better.

It seems like the major change of the patch was here:
https://github.com/kyprizel/ModSecurity/commit/bda7ad436ac0b89380157e936c2712ada1270fc3#diff-a80339e1bd9e20765a4f9539ae3c09ecR549

In your comment you said: 
'''
/* we can't run Host handler from here */
'''

I did not understood why we can't run set this host variable. Can you explain?

I made some comments along the patch.

**Comment by wanghm** [comment]
Hi, can anyone tell me if this issue has been solved in master branch?
I installed the newest modsecurity and nginx1.8.0.
And I got this error.

**Comment by zimmerle** [comment]
Hi @wanghm, the status of this pull request still open. Thanks for you interest. 

I recommend the utilization of "nginx_refactoring"  branch. 

https://github.com/SpiderLabs/ModSecurity/tree/nginx_refactoring

**Comment by zimmerle** [comment]
Hi @kyprizel,

Thank you again for you patch. It was **partially merged** into "nginx_refactoring" branch. I am closing this pull request.

**Pull request closed without merging**
