### PR TITLE
Use std::shared_ptr for variable resolution

### PR DESCRIPTION
**Pull request by WGH-**
`AnchoredSetVariable::resolve` is called for every rule (see `RuleWithOperator::evaluate`). The previous implementation allocated a new copy of every variable, which quickly added up. In my tests, `AnchoredSetVariable::resolve` function consumed 7.8% of run time.

`AnchoredSetVariable` (which is a multimap) values are never changed, only added. This means it's safe to store them in `std::shared_ptr`, and make `resolve` return `shared_ptr` pointing to the same object.

Other resolve implementation could also use this optimization by not allocating new objects, however, they are not hot spots, so this optimization was not implemented there.

In my benchmark, this raises performance from 117 requests per second to 131 RPS, and overhead is lowered from 7.8% to 2.4%.

As a bonus, replacing plain pointer with smart pointers make code cleaner, since using smart pointers makes manual deletes no longer necessary.

Additionally, `VariableOrigin` is now stored in plain `std::vector`, since it's wasteful to store structure containing just two integer values using `std::list<std::unique_ptr<T>>`.

Before (the thing to the left of `executeTransformations` labeled "modsecuri.."):
v3master
After:
stdsharedptr_after

SVG files for the flamegraphs: [flamegraphs.tar.gz](https://github.com/SpiderLabs/ModSecurity/files/4990382/flamegraphs.tar.gz)

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi, @WGH-

Please consider using **std::deque** instead of **std::vector** for the VariableOrigin as explained at: #2375.

That sounds like a good modification, we didn't change so much the _Variable class_ on 3.1 yet, so I think it will be easy to rebase that to 3.1-experimental. Do you mind?

Thank you for your work. Very nice to see the flame charts. Kudos :)

**Comment by martinhsv** [comment]
I'm skeptical that deque would be more performant here.  I would personally leave them as vector.

**Comment by WGH-** [comment]
I made a test. `std::deque` basically gives the same performance (slower within the margin of error: 130 RPS).

`std::deque` shines when you actually use it as a queue: i.e. append/remove items to/from either end. Sure, it also avoids reallocations when you append elements, but the count and the size of individual elements are too small here to matter.

**Comment by WGH-** [comment]
By the way, `AnchoredSetVariable` has a couple of places where the variable is inserted in front of the vector for no apparent reason. I think replacing it with `push_back` will have bigger impact.

https://github.com/SpiderLabs/ModSecurity/blob/0eb3c123f447b8787ea726ad4d4439018a07ee31/src/anchored_set_variable.cc#L83-L88

https://github.com/SpiderLabs/ModSecurity/blob/0eb3c123f447b8787ea726ad4d4439018a07ee31/src/anchored_set_variable.cc#L91-L102

I don't think the order of the resolved variables supposed to matter,  and even `AnchoredSetVariable::resolve` inserts new elements by iterating over `std::unordered_map`, which is, well, unorderdered, but replacing it with `push_back` still causes some test to fail:

```
  # File Name                                         Test Name                                                             Passed?
--- ---------                                         ---------                                                             -------
  1 offset-variable.json                              Variable offset - FILES_NAMES                                         failed!

Test failed. From: ../test/test-cases/regression/offset-variable.json.
Test name: Variable offset - FILES_NAMES.
Reason:
Error log was not matching the expected results.
Expecting: o0,8o0,8v491,8t:trimo0,16o0,16v709,16t:trim
<...>
Error log:
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(fiasdfasdfledata|filedata)' against variable `FILES_NAMES:filedata' (Value: `filedata' ) [file "offset-variable.json"] [line "2"] [id "1"] [rev ""] [msg "s"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "200.249.12.31"] [uri "/wheee/f i l e "] [unique_id "1596052147"] [ref "o0,16o0,16v709,16t:trimo0,8o0,8v491,8t:trim"]
```

**Comment by WGH-** [comment]
I have rebased it on top of v3/dev/3.1-experimental branch.

I have been unable to test it with my benchmark, because it crashes. Base v3/dev/3.1-experimental crashes as well, so it's not caused by the shared_ptr changes.
```
(gdb) bt
#0  0x00007ffff7c0cf16 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff7ea7d6f in modsecurity::RuleWithActions::executeTransformations (this=this@entry=0x5555565eeb00, trans=trans@entry=0x555564ca3390, in="%2F", Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
results=std::__cxx11::list) at rule_with_actions.cc:336
#2  0x00007ffff7ead9f4 in modsecurity::RuleWithOperator::evaluate (this=0x5555565eeb00, trans=0x555564ca3390) at rule_with_operator.cc:303
#3  0x00007ffff7e9bba4 in modsecurity::RulesSet::evaluate (this=0x5555555bc870, phase=phase@entry=3, t=t@entry=0x555564ca3390) at rules_set.cc:300
#4  0x00007ffff7e88303 in modsecurity::Transaction::processRequestBody (this=<optimized out>) at transaction.cc:985
#5  0x0000555555559a8c in process_transaction (it=0x7fffffffe080, modsecTransaction=0x555564ca3390, j=...) at benchmark.cc:103
#6  main (argc=<optimized out>, argv=<optimized out>) at benchmark.cc:194
(gdb) frame 1
#1  0x00007ffff7ea7d6f in modsecurity::RuleWithActions::executeTransformations (this=this@entry=0x5555565eeb00, trans=trans@entry=0x555564ca3390, in="%2F", results=std::__cxx11::list = {...}) at rule_with_actions.cc:336
336             if (dynamic_cast<actions::transformations::None *>(t)) {
```

**Comment by zimmerle** [comment]
> I made a test. `std::deque` basically gives the same performance (slower within the margin of error: 130 RPS).
> 
> `std::deque` shines when you actually use it as a queue: i.e. append/remove items to/from either end. Sure, it also avoids reallocations when you append elements, but the count and the size of individual elements are too small here to matter.

Thank you for having a test on it. My concern was about memory handling, but you have a point. @martinhsv also mentioned to me the possibility to use [.reserve()](https://en.cppreference.com/w/cpp/container/vector/reserve) to promptly pre-allocated the vector resources whenever we are able to measure (or educated guess its size).

We do use it here:
https://github.com/SpiderLabs/ModSecurity/blob/5824470768e73d438a5db03b7a6eb24d7c795097/src/anchored_set_variable.cc#L31-L36

**Comment by zimmerle** [comment]
> By the way, `AnchoredSetVariable` has a couple of places where the variable is inserted in front of the vector for no apparent reason. I think replacing it with `push_back` will have bigger impact.
> 
> https://github.com/SpiderLabs/ModSecurity/blob/0eb3c123f447b8787ea726ad4d4439018a07ee31/src/anchored_set_variable.cc#L83-L88
> 
> https://github.com/SpiderLabs/ModSecurity/blob/0eb3c123f447b8787ea726ad4d4439018a07ee31/src/anchored_set_variable.cc#L91-L102
> 
> I don't think the order of the resolved variables supposed to matter, and even `AnchoredSetVariable::resolve` inserts new elements by iterating over `std::unordered_map`, which is, well, unorderdered, but replacing it with `push_back` still causes some test to fail:
> 
> ```
>   # File Name                                         Test Name                                                             Passed?
> --- ---------                                         ---------                                                             -------
>   1 offset-variable.json                              Variable offset - FILES_NAMES                                         failed!
> 
> Test failed. From: ../test/test-cases/regression/offset-variable.json.
> Test name: Variable offset - FILES_NAMES.
> Reason:
> Error log was not matching the expected results.
> Expecting: o0,8o0,8v491,8t:trimo0,16o0,16v709,16t:trim
> <...>
> Error log:
> ModSecurity: Warning. Matched "Operator `Rx' with parameter `(fiasdfasdfledata|filedata)' against variable `FILES_NAMES:filedata' (Value: `filedata' ) [file "offset-variable.json"] [line "2"] [id "1"] [rev ""] [msg "s"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "200.249.12.31"] [uri "/wheee/f i l e "] [unique_id "1596052147"] [ref "o0,16o0,16v709,16t:trimo0,8o0,8v491,8t:trim"]
> ```

Placing that on my TODO list, getting back to you in a few.

**Comment by zimmerle** [comment]
Rebased this patch here: be4cba2a375d22c74866c076d75e4b99eeacf8a1


It seems that it introduces an issue regarding the [RunTimeString](https://github.com/SpiderLabs/ModSecurity/blob/v3/dev/3.1-experimental/src/run_time_string.cc) execution. 

The test case: [regression/issue-1844.json](https://github.com/SpiderLabs/ModSecurity/blob/v3/dev/3.1-experimental/test/test-cases/regression/issue-1844.json#L241-L287) is falling with a core dump.

https://github.com/SpiderLabs/ModSecurity/blob/b32182940d558db803c063575552621bc061380b/test/test-cases/regression/issue-1844.json#L241-L287

back trace below:
```
#0  0x00007ffff7e94f5b in std::__uniq_ptr_impl<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >::_M_ptr (this=<optimized out>) at rule_with_actions.cc:399
#1  std::unique_ptr<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >::get (this=<optimized out>) at /usr/include/c++/10.1.0/bits/unique_ptr.h:421
#2  std::unique_ptr<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >::operator bool (this=<optimized out>) at /usr/include/c++/10.1.0/bits/unique_ptr.h:435
#3  std::operator==<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >(std::unique_ptr<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> > const&, decltype(nullptr)) (__x=...) at /usr/include/c++/10.1.0/bits/unique_ptr.h:760
#4  modsecurity::actions::ActionWithRunTimeString::getEvaluatedRunTimeString[abi:cxx11](modsecurity::Transaction*) const (transaction=<optimized out>, this=<optimized out>) at ../src/actions/action_with_run_time_string.h:53
#5  modsecurity::RuleWithActions::getMessage[abi:cxx11](modsecurity::Transaction*) const (this=0x555555646c60, t=0x5555556651a0) at rule_with_actions.cc:399
#6  0x00007ffff7e3ac2f in modsecurity::variables::Rule_DictElement::msg (t=<optimized out>, rule=<optimized out>, l=0x7fffffffafa0) at ../src/variables/rule.h:124
#7  0x00007ffff7e91f10 in modsecurity::RunTimeString::evaluate[abi:cxx11](modsecurity::Transaction*) (this=0x555555645350, transaction=transaction@entry=0x5555556651a0) at run_time_string.cc:58
#8  0x00007ffff7ec62e1 in modsecurity::actions::ActionWithRunTimeString::getEvaluatedRunTimeString[abi:cxx11](modsecurity::Transaction*) const (transaction=0x5555556651a0, this=0x555555682d60) at ../src/actions/action_with_run_time_string.h:53
#9  modsecurity::actions::SetVar::execute (this=0x555555682d60, t=0x5555556651a0) at actions/set_var.cc:50
#10 0x00007ffff7e9609d in modsecurity::RuleWithActions::executeActionsIndependentOfChainedRuleResult (this=0x55555558ffc0, trans=0x5555556651a0) at rule_with_actions.cc:207
#11 0x00007ffff7e9cb0e in modsecurity::RuleWithOperator::evaluate (this=0x55555558ffc0, trans=<optimized out>) at rule_with_operator.cc:338
#12 0x00007ffff7e89724 in modsecurity::RulesSet::evaluate (this=<optimized out>, phase=phase@entry=3, t=t@entry=0x5555556651a0) at /usr/include/c++/10.1.0/bits/shared_ptr_base.h:1324
#13 0x00007ffff7e76d1a in modsecurity::Transaction::processRequestBody (this=0x5555556651a0) at transaction.cc:984
#14 0x000055555555db39 in perform_unit_test (test=<optimized out>, tests=<optimized out>, res=<optimized out>, count=<optimized out>) at regression/regression.cc:344
#15 0x000055555555976f in main (argc=<optimized out>, argv=<optimized out>) at regression/regression.cc:548
>>> bt
#0  0x00007ffff7e94f5b in std::__uniq_ptr_impl<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >::_M_ptr (this=<optimized out>) at rule_with_actions.cc:399
#1  std::unique_ptr<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >::get (this=<optimized out>) at /usr/include/c++/10.1.0/bits/unique_ptr.h:421
#2  std::unique_ptr<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >::operator bool (this=<optimized out>) at /usr/include/c++/10.1.0/bits/unique_ptr.h:435
#3  std::operator==<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> >(std::unique_ptr<modsecurity::RunTimeString, std::default_delete<modsecurity::RunTimeString> > const&, decltype(nullptr)) (__x=...) at /usr/include/c++/10.1.0/bits/unique_ptr.h:760
#4  modsecurity::actions::ActionWithRunTimeString::getEvaluatedRunTimeString[abi:cxx11](modsecurity::Transaction*) const (transaction=<optimized out>, this=<optimized out>) at ../src/actions/action_with_run_time_string.h:53
#5  modsecurity::RuleWithActions::getMessage[abi:cxx11](modsecurity::Transaction*) const (this=0x555555646c60, t=0x5555556651a0) at rule_with_actions.cc:399
#6  0x00007ffff7e3ac2f in modsecurity::variables::Rule_DictElement::msg (t=<optimized out>, rule=<optimized out>, l=0x7fffffffafa0) at ../src/variables/rule.h:124
#7  0x00007ffff7e91f10 in modsecurity::RunTimeString::evaluate[abi:cxx11](modsecurity::Transaction*) (this=0x555555645350, transaction=transaction@entry=0x5555556651a0) at run_time_string.cc:58
#8  0x00007ffff7ec62e1 in modsecurity::actions::ActionWithRunTimeString::getEvaluatedRunTimeString[abi:cxx11](modsecurity::Transaction*) const (transaction=0x5555556651a0, this=0x555555682d60) at ../src/actions/action_with_run_time_string.h:53
#9  modsecurity::actions::SetVar::execute (this=0x555555682d60, t=0x5555556651a0) at actions/set_var.cc:50
#10 0x00007ffff7e9609d in modsecurity::RuleWithActions::executeActionsIndependentOfChainedRuleResult (this=0x55555558ffc0, trans=0x5555556651a0) at rule_with_actions.cc:207
#11 0x00007ffff7e9cb0e in modsecurity::RuleWithOperator::evaluate (this=0x55555558ffc0, trans=<optimized out>) at rule_with_operator.cc:338
#12 0x00007ffff7e89724 in modsecurity::RulesSet::evaluate (this=<optimized out>, phase=phase@entry=3, t=t@entry=0x5555556651a0) at /usr/include/c++/10.1.0/bits/shared_ptr_base.h:1324
#13 0x00007ffff7e76d1a in modsecurity::Transaction::processRequestBody (this=0x5555556651a0) at transaction.cc:984
#14 0x000055555555db39 in perform_unit_test (test=<optimized out>, tests=<optimized out>, res=<optimized out>, count=<optimized out>) at regression/regression.cc:344
#15 0x000055555555976f in main (argc=<optimized out>, argv=<optimized out>) at regression/regression.cc:548
```

**Comment by zimmerle** [comment]
Updated to 47be22e62a4b2ab06dae1075c2187f47b462b2f1

**Comment by zimmerle** [comment]
> I have rebased it on top of v3/dev/3.1-experimental branch.
> 
> I have been unable to test it with my benchmark, because it crashes. Base v3/dev/3.1-experimental crashes as well, so it's not caused by the shared_ptr changes.
> 
> ```
> (gdb) bt
> #0  0x00007ffff7c0cf16 in __dynamic_cast () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #1  0x00007ffff7ea7d6f in modsecurity::RuleWithActions::executeTransformations (this=this@entry=0x5555565eeb00, trans=trans@entry=0x555564ca3390, in="%2F", Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
> results=std::__cxx11::list) at rule_with_actions.cc:336
> #2  0x00007ffff7ead9f4 in modsecurity::RuleWithOperator::evaluate (this=0x5555565eeb00, trans=0x555564ca3390) at rule_with_operator.cc:303
> #3  0x00007ffff7e9bba4 in modsecurity::RulesSet::evaluate (this=0x5555555bc870, phase=phase@entry=3, t=t@entry=0x555564ca3390) at rules_set.cc:300
> #4  0x00007ffff7e88303 in modsecurity::Transaction::processRequestBody (this=<optimized out>) at transaction.cc:985
> #5  0x0000555555559a8c in process_transaction (it=0x7fffffffe080, modsecTransaction=0x555564ca3390, j=...) at benchmark.cc:103
> #6  main (argc=<optimized out>, argv=<optimized out>) at benchmark.cc:194
> (gdb) frame 1
> #1  0x00007ffff7ea7d6f in modsecurity::RuleWithActions::executeTransformations (this=this@entry=0x5555565eeb00, trans=trans@entry=0x555564ca3390, in="%2F", results=std::__cxx11::list = {...}) at rule_with_actions.cc:336
> 336             if (dynamic_cast<actions::transformations::None *>(t)) {
> ```

@WGH- do you mind to test it again against the top of v3.1-experimental. If it still failing, can you share the set of rules that you are using? I am not able to reproduce it here.

**Comment by WGH-** [comment]
> It seems that it introduces an issue regarding the RunTimeString execution.

I'm having the same crash in my benchmark in base v3.1-experimental. I suppose this patch is not at fault, it just shuffled something a bit so the underlying problem surfaces in the regression test.

I'll create a minimal reproduction, and report back to #2376

**Comment by zimmerle** [comment]
It seems that **push_back** was used together with **std::make_shared** on different places, those could be replaced with **emplace_back**. I am having it tested here.

**Comment by WGH-** [comment]
`std::make_shared<T>(...)` is more efficient than `std::shared_ptr(new T(...))`, since the former will do only one heap allocation instead of two, though.

**Comment by WGH-** [comment]
@zimmerle Did you already merge it into v3/dev/3.1-experimental? Or what happened?

**Comment by zimmerle** [comment]
> @zimmerle Did you already merge it into v3/dev/3.1-experimental? Or what happened?

Yes. It is merged on v3.1-experimental. As shared pointer I have delayed the variable resolution to the next minute if needed. 

Listed here-
https://github.com/SpiderLabs/ModSecurity/blob/abf59f4b84992195e9ba58c378d8ab4441f73b6b/headers/modsecurity/variable_value.h#L51-L86

I did not collected the numbers yet, trying to make the branch stable first.

Other change that I did, was this: cc5d3f510625df09a21aadbdfe1c644cd10fb20f

**Comment by zimmerle** [comment]
I am going to close this. We can track the performance numbers in a separated issue, if needed.

Thank you @WGH- .

**Comment by WGH-** [comment]
It's just the state of this PR after you force-pushed some diverged branch utterly confused me. It's clear now, thanks,

**Comment by zimmerle** [comment]
> R after you force-pushed some diverged branch utterly confused me. It's clear now, thanks,

v3.1-experimental is being rebased against v3/master from time to time, indeed it is confusing.

**Pull request closed without merging**
