### PR TITLE
Fixed IPv4 address parsing when port is present at end of address

### PR DESCRIPTION
**Pull request by culyerr**
Relates to #1109

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi @cylyerr,

Thanks for you patch. It is currently being tested by our buildbots.

**Comment by zimmerle** [comment]
Hi @culyerr,

This function "tree_contains_ip" is not only used by IIS. It is used by our different ports: for Apache, NGINX, and others. We may also expect to receive an IPv6 as input of that function.

I believe that this bug that you want to address, may related to the fact that the IP address should never ever come with the port at that stage. Most likely the update needs to be made in the IIS specific code. So that we can get rid of the port in the earlier stages of ModSecurity processing.

Testing the patch I got 2582 unit tests failing. Please, have a look at:
http://www.modsecurity.org/developers/buildbot/builders/Linux32%20-%20Nginx%20%28Stable%29/builds/255/steps/unit%20test_1/logs/stdio

**Comment by zimmerle** [comment]
@culyerr if you want to discuss it, please reach me (zimmerle) or csanders on #modsecurity at FreeNode.

**Comment by culyerr** [comment]
Thanks. I am picking this up again now and will look to implement the check in the IIS specific code.

**Comment by zimmerle** [comment]
@culyerr Nice ;) if you need something we are at: https://modsecurity.slack.com/

**Pull request closed without merging**
