### PR TITLE
Process request body for HTTP PUT method - fixes #939

### LINKED ISSUE #939: PUT body not processed
According to the following, PUT body is not processed, only POST body is. In many REST services, PUT is used very frequently and SQL injection (and other) attacks can be caught if mod security processes these requests.

https://github.com/SpiderLabs/ModSecurity/blob/master/nginx/modsecurity/ngx_http_modsecurity.c#L1011-L1021

(thanks very much Felipe Costa for the help in identifying this out)

More information in this thread here: http://sourceforge.net/p/mod-security/mailman/message/34499810/

### PR DESCRIPTION
**Pull request by sdamodharan**
For processing HTTP PUT body fixes #939

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi @sdamodharan,

Sorry for the delay. I believe that this sanity validation to ignore the PUT method was placed there on purpose as the PUT method was not being handled well, did you had a chance to test it?

Btw, did you saw the ModSecurity-nginx connector already?

**Comment by sdamodharan** [comment]
@zimmerle the PUT method works fine in nginx+modsecurity and we have been using it in production for nearly one month.

I haven't focused much into the nginx connector. But, with the 2.x version of ModSecurity being widely adopted in production, I thought this might help people to get started easily with it, without the need to hold back due to the lack of PUT support in ModSecurity 2.x

**Comment by GayathriMAKK** [comment]
Hi @zimmerle,

We have modsecurity 2.9.1 on Nginx which fails to parse the body of PUT requests. Is there a sanity validation to ignore PUT method and if yes, can you point us to the rule?

thanks,
Gayathri

**Comment by sdamodharan** [comment]
Hi Gayathri,

If you want to bypass ModSecurity for the PUT method, you can do that via
Nginx conf.

But, if thats not the case, if you want to sanitise the incoming PUT
requests, you can apply the above proposed patch to ModSecurity 2.9.1 and
recompile it against Nginx.

Also you can give ModSec3 nginx connector a try.

Sent from my iPhone

On 27-Jan-2017, at 06:38, GayathriMAKK <notifications@github.com> wrote:

Hi @zimmerle <https://github.com/zimmerle>,

We have modsecurity 2.9.1 on Nginx which fails to parse the body of PUT
requests. Is there a sanity validation to ignore PUT method and if yes, can
you point us to the rule?

thanks,
Gayathri

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SpiderLabs/ModSecurity/pull/1261#issuecomment-275563169>,
or mute the thread

**Comment by GayathriMAKK** [comment]
Hi @sdamodharan,

If we need to bypass ModSecurity for the PUT method, does it mean we ignore PUT method altogether from modsec rules? 
I think the allowed HTTP verbs are specified in "crs-setup.conf" and if we exclude PUT from this list,  it will not allow Nginx to accept any PUT requests. 

Based on https://github.com/SpiderLabs/ModSecurity-nginx, Nginx connector is still not stable and we need a fix for our production environment hence may resort to the patch on our existing version.
Thanks,
Gayathri

**Comment by victorhora** [comment]
> But, if thats not the case, if you want to sanitise the incoming PUT
> requests, you can apply the above proposed patch to ModSecurity 2.9.1 and
> recompile it against Nginx.

Hi @sdamodharan I've tested your proposed patch against Nginx 1.11.10 and ModSecurity 2.9.1 and I couldn't confirm the behavior you've mentioned above.

Even though I have http_dav_module enabled on Nginx and correctly processing PUT requests, I can confirm I can match on the request line (e.g. the filename or parameters) but the body doesn't seem to be inspected.

Could you please share your configuration and if possible your matching SecRule so I can double check on my side?

Thanks.

**Comment by zimmerle** [comment]
Hi @sdamodharan,

I am closing this pull request as now we have the libModSecurity and the workable ModSecurity for nginx. Available here:
https://github.com/SpiderLabs/ModSecurity-nginx

**Pull request closed without merging**
