### PR TITLE
issue.

### PR DESCRIPTION
**Pull request by 877509395**

### CODE REVIEW

**Comment by 877509395** [comment]
So if multimatch is one of actions, correct rule message is not possible. 

this is not a pull request. I just want to show issue.

**Comment by 877509395** [comment]
https://github.com/coreruleset/coreruleset/blob/v3.4/dev/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
rule 942100

wget www.s.com.cn?a="a or 1=1"   can trigger audit log with data="", it should not.

**Comment by martinhsv** [comment]
Hello @877509395 ,

I'm not certain, but it sounds like you are reporting the same thing as this open issue: https://github.com/SpiderLabs/ModSecurity/issues/2573

Feel free to let me know if I am mistaken.  If so, could you then also describe how your use case is different from that other issue.

**Comment by 877509395** [comment]
Yes, they are the same.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SpiderLabs/ModSecurity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月31日(星期天) 凌晨2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SpiderLabs/ModSecurity] issue. (PR #2634)





 
Hello @877509395 ,
 
I'm not certain, but it sounds like you are reporting the same thing as this open issue: #2573
 
Feel free to let me know if I am mistaken.  If so, could you then also describe how your use case is different from that other issue.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 877509395** [comment]
not a PR, close.

**Pull request closed without merging**
