### PR TITLE
Option to disable logging of notice info at start (versions, ...) in error log.

### PR DESCRIPTION
**Pull request by marcstern**
Also fixed typo in configure.ac in $log_server_context

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi @marcstern,

I am not able to foresee where this specific option can cause a benefit. Can you enlighten me ?

**Comment by marcstern** [comment]
This information is useless when you have a good change control in place and takes a lot of space in the log when you restart the server several times a day

**Comment by zimmerle** [comment]
Hi @marcstern,

Maintain a lot of options in the configuration file is tricker. I would recommend you to pass the log over a pipeline where you can filter the log to save what is interesting to you. It seems to me that this request is particular interesting to your environment. Please explain why a filter via pipe is not interesting to you.

**Comment by marcstern** [comment]
performance on high load

**Comment by zimmerle** [comment]
We do have very high load servers running logs into pipes and they work like a charm. The expensive computation is actually save the data to the disk (or SSD). The filter is negligible. What are you using as a the pipe application?

**Pull request closed without merging**
