### PR TITLE
Pull request for ModSecurity for Java

### PR DESCRIPTION
**Pull request by mihaipitu**
Pull request for merging with master branch

### CODE REVIEW

**Comment by jianjin** [comment]
any plan merge this pull request? or Do i have any other choice to use ModSecurity directly from JVM?

**Comment by zimmerle** [comment]
Hi @jianjin, are you current using this implementation ?

**Comment by jianjin** [comment]
Not Yet. I am doing some investigation. Just not sure if this Pull request is a right way to go or not.

**Comment by zimmerle** [comment]
We have more information about it here: https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-for-Java---BETA-Testers-Needed/

If you use/test it, please provide some feedback.

**Comment by jianjin** [comment]
we are trying to buy a commercial rule set, we paid, but it is crazy that we could not get it. We sent email, phone call, nothing help.

**Comment by zimmerle** [comment]
Hi @jianjin, can you describe a little bit the issue that you are current facing? You are trying to use this ModSecurity for Java version ?

**Comment by zimmerle** [comment]
This pull request was merged into the branch: "ModSecurity_for_Java". 

Keeping the set of patches into this new branch, will make easy to update the base version of ModSecurity. In fact, that branch is now up-to-date regarding our master branch

The branch is available here:
https://github.com/SpiderLabs/ModSecurity/tree/ModSecurity_for_Java

**Pull request closed without merging**
