### PR TITLE
Actually fix setvar parsing of quoted data

### PR DESCRIPTION
**Pull request by victorhora**
Proper fix for #1733 on top of #1759

### CODE REVIEW

**Comment by defanator** [comment]
@victorhora @zimmerle going to check this one in a few. Will provide an update here.

**Comment by defanator** [comment]
@victorhora @zimmerle this PR fixes the issue (I've been building libmodsecurity with `--enable-parser-generation` to ensure everything is ok though). Will check again without regenerating the parser shortly.

**Comment by defanator** [comment]
@victorhora @zimmerle it works fine without rebuilding parser, so I think we're good here. Thanks guys!

**Comment by zimmerle** [comment]
normalized bison version and re-submitted to tests. at: v3/dev/pull_1775

**Comment by zimmerle** [comment]
Merged! Thanks!

**Pull request closed without merging**
