### PR TITLE
Reformat the README to Markdown

### PR DESCRIPTION
**Pull request by hsluoyz**
Fix: https://github.com/SpiderLabs/ModSecurity/issues/1857

### CODE REVIEW

**Comment by hsluoyz** [comment]
@victorhora

**Comment by victorhora** [comment]
IMHO this PR could be welcome. 

But before further evaluation/acceptance, please take into consideration https://github.com/SpiderLabs/ModSecurity/issues/1848#issuecomment-415146396 and see if you want to add any further changes/commits.

Thanks for your contribution :)

**Comment by hsluoyz** [comment]
Thanks for the advice. I have updated the dependencies based on refactory of 2.9.2 release: https://github.com/SpiderLabs/ModSecurity/pull/1856/commits/7c43a27b319ffa565d00b2f9d7f1537447b7469e

**Comment by victorhora** [comment]
Merged as of https://github.com/SpiderLabs/ModSecurity/commit/e0a087b54036537f1145e86a602094d8a3d2933f

Thanks!

**Pull request closed without merging**
