### PR TITLE
Json Body Sanitizing

### PR DESCRIPTION
**Pull request by florian-eichelberger**
The change should allow sanitizing the JSON Body requests for the apache module by using native logging (as this was requested earlier and is used locally here).

### CODE REVIEW

**Comment by zimmerle** [comment]
Hi @florian-eichelberger,

Thank you for the patch! That is indeed a good feature to have.

**Comment by florian-eichelberger** [comment]
Please be so kind and tell me how to fix the Travis CI build error :)

**Comment by zimmerle** [comment]
@florian-eichelberger we have two different continuous integration in place: 

1 - Buildbots
2 - Travis

The Buildbots are meant to run for v2 builds while the Travis is only used by v3. That is why it is failing for your branch. The Buildbots are testing your code now:
http://www.modsecurity.org/developers/buildbot/waterfall

**Comment by zimmerle** [comment]
Hi @florian-eichelberger,

Buildbots went ok ;) I am moving your patch to the branch:  [v2/exp/json_sanitizer](https://github.com/SpiderLabs/ModSecurity/tree/v2/exp/json_sanitizer). It will be on hold till out next release.

**Pull request closed without merging**
